language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - python -m textblob.download_corpora
  - python app/sentiment/train.py
script:
- python -m pytest -rav tests
